import type { SettingsMap } from '@/types';

/**
 * Standardverdier for alle redigerbare tekster.
 *
 * Brukes hvis en innstilling ikke finnes i databasen ennå, eller hvis
 * Supabase ikke svarer. Speiler supabase/migrations/0004_innhold.sql —
 * begge deler genereres fra samme kilde.
 */
export const DEFAULT_SETTINGS: SettingsMap = {
  company_name: 'Fredrikshald Mat & Catering UB',
  tagline: 'Ungdomsbedrift ved Restaurant- og matfag',
  city: 'Halden',
  address: '',
  logo_url: '',
  org_number: '',
  email: 'fredrikshaldmatogcatering@gmail.com',
  phone: '',
  instagram_handle: '@fredrikshaldmatogcatering',
  instagram_url: 'https://www.instagram.com/fredrikshaldmatogcatering/',
  facebook_name: 'Fredrikshald Mat & Catering',
  facebook_url: 'https://www.facebook.com/',
  footer_text: 'Fredrikshald Mat & Catering UB er en elevdrevet ungdomsbedrift ved Restaurant- og matfag i Halden.',
  footer_note: 'Ungdomsbedrift ved Restaurant- og matfag',
  instagram_band_title: 'Følg oss på Instagram',
  instagram_band_text: 'Der legger vi ut bilder fra det vi lager:',
  instagram_band_button: 'Åpne Instagram',
  hero_eyebrow: 'Ungdomsbedrift i Halden',
  hero_title: 'Mat laget av elever, til dine anledninger',
  hero_description: 'Vi er en ungdomsbedrift ved Restaurant- og matfag i Halden. Vi lager maten selv, fra bunn, og leverer til selskaper, møter og arrangementer i nærområdet.',
  hero_cta_primary: 'Ta kontakt',
  hero_cta_secondary: 'Se maten vår',
  hero_fact1_title: 'Elevdrevet',
  hero_fact1_text: 'Ungdomsbedrift ved Restaurant- og matfag',
  hero_fact2_title: 'Laget fra bunn',
  hero_fact2_text: 'Vi lager maten selv',
  hero_fact3_title: 'Lokalt',
  hero_fact3_text: 'Vi holder til i Halden',
  home_about_eyebrow: 'Om oss',
  home_about_title: 'En ungdomsbedrift med et ekte kjøkken bak seg',
  home_about_text: 'Vi er elever ved Restaurant- og matfag, og driver Fredrikshald Mat & Catering UB som en del av utdanningen vår. Vi lager maten selv, og gjennom bedriften får vi praktisk erfaring med planlegging, matlaging og servering til ekte kunder.',
  home_about_link: 'Les mer om oss',
  home_step1_title: 'Du tar kontakt',
  home_step1_text: 'Send oss en e-post med hva slags arrangement det er, omtrent hvor mange dere er og når det skjer.',
  home_step2_title: 'Vi setter sammen et forslag',
  home_step2_text: 'Vi foreslår en meny som passer anledningen, og tar hensyn til allergier og ønsker underveis.',
  home_step3_title: 'Vi lager maten',
  home_step3_text: 'Elevene hos oss lager maten selv, og vi avtaler henting eller levering når dere trenger den.',
  home_events_eyebrow: 'Hva vi kan lage mat til',
  home_events_title: 'Fra bursdag til bedriftslunsj',
  home_events_text: 'Vi setter sammen maten etter anledningen. Her er noen av arrangementene vi gjerne lager mat til.',
  home_events_button: 'Se alle arrangementer',
  home_menu_eyebrow: 'Menyen',
  home_menu_title: 'Et utvalg fra menyen',
  home_menu_text: 'Menyen tilpasses hvert oppdrag. Under ser du noe av det vi lager — hele menyen finner du på egen side.',
  home_menu_button: 'Se hele menyen',
  home_gallery_eyebrow: 'Galleri',
  home_gallery_title: 'Bilder fra kjøkkenet',
  home_gallery_text: 'Alle bilder på nettsiden er våre egne.',
  home_gallery_button: 'Se hele galleriet',
  home_reviews_eyebrow: 'Anmeldelser',
  home_reviews_title: 'Hva kundene sier',
  home_reviews_button: 'Alle anmeldelser',
  cta_title: 'Skal dere ha mat til noe?',
  cta_text: 'Fortell oss kort hva slags arrangement det er, hvor mange dere er og når det skjer — så kommer vi tilbake til deg.',
  cta_primary_label: 'Be om tilbud',
  cta_secondary_label: 'Send forespørsel',
  about_eyebrow: 'Om oss',
  about_title: 'Vi er elever ved Restaurant- og matfag',
  about_description: 'Fredrikshald Mat & Catering UB er en ungdomsbedrift. Vi driver bedriften selv, og lager maten selv.',
  about_body_title: 'Hvem vi er',
  about_body_1: 'Vi går på Restaurant- og matfag, og driver Fredrikshald Mat & Catering UB som en del av utdanningen vår. En ungdomsbedrift fungerer som en vanlig bedrift: vi har ansvaret for planlegging, innkjøp, matlaging, kundekontakt og økonomi.',
  about_body_2: 'Vi lager maten selv. Det betyr at det er vi som står på kjøkkenet, og at maten dere får er laget fra bunn av oss som elever.',
  about_body_3: 'Målet vårt er å levere god mat til arrangementer i Halden og nærområdet — og samtidig få praktisk erfaring med faget vi utdanner oss i.',
  about_value1_title: 'Vi lager maten selv',
  about_value1_text: 'Alt vi leverer er laget av oss. Det er elevene i bedriften som planlegger, forbereder og lager maten.',
  about_value2_title: 'Vi lærer av å drive på ordentlig',
  about_value2_text: 'Ungdomsbedrift betyr at vi driver bedriften selv, med ekte kunder og ekte frister. Det er slik vi får praktisk erfaring.',
  about_value3_title: 'Vi holder til i Halden',
  about_value3_text: 'Vi er lokale, og ønsker å lage mat til arrangementer i nærområdet vårt.',
  about_team_eyebrow: 'Teamet',
  about_team_title: 'Elevene bak bedriften',
  about_team_text: 'Her legger vi ut bilder av oss som jobber i bedriften. Bildene lastes opp under Galleri i adminpanelet.',
  menu_eyebrow: 'Menyen',
  menu_title: 'Maten vi lager',
  menu_description: 'Menyen er et utgangspunkt. Vi setter den sammen etter anledningen, antall gjester og eventuelle allergier — ta kontakt, så finner vi ut av det sammen.',
  menu_footnote: 'Allergener er merket på hver rett. Har du allergier eller ønsker som ikke står her, si fra når du tar kontakt — så tilpasser vi maten. Priser som ikke er oppgitt avtales ut fra antall gjester og innhold.',
  menu_empty_title: 'Menyen legges ut snart',
  menu_empty_text: 'Vi holder på å sette sammen menyen vår. Ta gjerne kontakt i mellomtiden, så forteller vi hva vi kan lage til arrangementet ditt.',
  menu_cta_title: 'Vil du ha et forslag til meny?',
  menu_cta_text: 'Fortell oss om anledningen, så setter vi sammen et forslag.',
  menu_cta_label: 'Be om menyforslag',
  gallery_eyebrow: 'Galleri',
  gallery_title: 'Bilder fra kjøkkenet vårt',
  gallery_description: 'Alle bildene her er våre egne, tatt av det vi faktisk har laget.',
  gallery_empty_title: 'Vi legger ut bilder snart',
  gallery_empty_text: 'Galleriet fylles med bilder av maten vi lager. Følg oss gjerne på Instagram i mellomtiden.',
  events_eyebrow: 'Arrangementer',
  events_title: 'Hva vi kan lage mat til',
  events_description: 'Under ser du hva vi tilbyr. Står ikke anledningen din på listen, ta kontakt likevel — vi hører gjerne fra deg.',
  events_guide_eyebrow: 'Veiviser',
  events_guide_title: 'Hva passer til ditt arrangement?',
  events_guide_description: 'Svar på tre korte spørsmål, så foreslår vi hvor du kan begynne. Dette er kun ment som inspirasjon, og sender ingen bestilling.',
  events_guide_note: 'Dette er kun et forslag til inspirasjon — ingen bestilling er sendt.',
  reviews_eyebrow: 'Anmeldelser',
  reviews_title: 'Hva kundene våre sier',
  reviews_description: 'Har du prøvd maten vår? Vi setter stor pris på om du deler noen ord.',
  reviews_form_title: 'Skriv en anmeldelse',
  reviews_form_text: 'Alle anmeldelser leses gjennom før de publiseres, så det kan ta litt tid før din dukker opp her.',
  reviews_empty_title: 'Ingen anmeldelser ennå',
  reviews_empty_text: 'Vi er en ny ungdomsbedrift, og har ikke fått anmeldelser ennå. Er du den første som vil dele en tilbakemelding, blir vi glade.',
  reviews_thanks: 'Takk for anmeldelsen. Den blir gjennomgått før den publiseres.',
  contact_eyebrow: 'Kontakt',
  contact_title: 'Ta kontakt med oss',
  contact_description: 'Alle forespørsler går på e-post. Fortell oss om anledningen, så kommer vi tilbake til deg.',
  contact_info_title: 'Kontaktinformasjon',
  contact_button_label: 'Ta kontakt på e-post',
  contact_response_note: 'Vi svarer så raskt vi kan. Vi er elever, så det kan gå litt tid i skoletiden.',
  contact_form_title: 'Send en forespørsel',
  contact_form_text: 'Fyll ut det du vet så langt. Skjemaet setter sammen en e-post du sender selv — vi tar ikke imot bestillinger eller betaling på nettsiden.',
  contact_faq_title: 'Godt å vite',
  contact_calendar_title: 'Når vi er opptatt',
  contact_calendar_text: 'Dagene som er merket, har vi allerede booket opp eller er borte. Ta gjerne kontakt likevel — noen ganger får vi det til.',
  faq_eyebrow: 'Vanlige spørsmål',
  faq_title: 'Spørsmål vi ofte får',
  faq_description: 'Står ikke svaret her, er det bare å ta kontakt — vi svarer gjerne.',
  privacy_eyebrow: 'Personvern',
  privacy_title: 'Personvern og informasjonskapsler',
  privacy_description: 'Kort om hvilke opplysninger nettsiden vår behandler, og hvorfor.',
  privacy_body: '## Hvem er ansvarlig?\nFredrikshald Mat & Catering UB er ansvarlig for opplysningene som behandles på denne nettsiden. Du når oss på fredrikshaldmatogcatering@gmail.com.\n\n## Informasjonskapsler (cookies)\nDen offentlige delen av nettsiden bruker ingen informasjonskapsler til analyse, markedsføring eller sporing. Vi har ingen sporingsverktøy og deler ingen opplysninger med annonsører.\n\nAdminpanelet, som kun brukes av oss, setter en teknisk nødvendig informasjonskapsel for å holde innloggingen i gang. Den brukes ikke til noe annet.\n\n## Kontaktskjemaet\nKontaktskjemaet sender ingenting til oss automatisk. Det setter sammen en e-post og åpner e-postprogrammet ditt, slik at du sender den selv. Opplysningene du skriver inn lagres ikke på nettsiden.\n\nSender du oss en e-post, oppbevarer vi den så lenge vi trenger den for å svare deg og eventuelt gjennomføre oppdraget.\n\n## Anmeldelser\nSender du inn en anmeldelse, lagrer vi navnet du oppgir, vurderingen, teksten og eventuell type arrangement. Anmeldelsen blir lest gjennom før den eventuelt publiseres på nettsiden.\n\nFor å hindre søppelinnlegg lagrer vi også en kryptert verdi utledet av IP-adressen. Den kan ikke regnes tilbake til IP-adressen din, og brukes kun til å begrense hvor mange anmeldelser som kan sendes inn på kort tid. Verdien slettes automatisk etter sju dager.\n\nVil du at en anmeldelse skal fjernes, send oss en e-post, så sletter vi den.\n\n## Hvor lagres dataene?\nNettsiden driftes hos Vercel, og innhold og bilder lagres hos Supabase. Begge er databehandlere for oss.\n\n## Dine rettigheter\nDu kan be om innsyn i, retting av eller sletting av opplysninger vi har om deg. Ta kontakt på e-post, så ordner vi det. Mener du at vi behandler opplysninger feil, kan du klage til Datatilsynet.',
  notfound_title: 'Oi, denne siden finnes ikke',
  notfound_text: 'Kanskje lenken er gammel, eller så har vi flyttet på noe. Prøv en av lenkene under.',
};
